### ISSUE TITLE
Hi, kokodak!

### ISSUE THREAD

**Issue by dooboocookie** [kokodak/kokodak#12]
녀석들이 말하는 '새 시대' 란 건 엿 같은 얘기다. 해적이 꿈을 꾸는 시대가 끝난다고....?!사람의 꿈은!!! 끝나지 않아!!!! 다른 사람을 능가하는 것도 쉽지가 않아! 비웃음을 사면서 가면 좀 어떠냐!높은 곳을 향하다 보면 주먹을 내지 말아야 할 싸움도 있는 법이지. 어이, 그렇지 않냐! 어이쿠, 방해였나 보군. 갈 길이 급하겠지?
갈 수 있으면 좋겠군, 하늘섬에! 제하하하하하!

**Comment by kokodak** [comment]
Hi! This is kokodak Bot. Please wait a moment, your guestbook comment is being registered.

**Comment by kokodak** [comment]
Thank you for your contribution!
