### ISSUE TITLE
If there were 8 billion fans of kokodak, I would be the one of them.

### ISSUE THREAD

**Issue by bagzaru** [kokodak/kokodak#13]
If there are 8 billion fans of kokodak in the world, I would be the one of them.
If there are a million fans of kokodak in the world, I would be the one of them.
If there are a thousand fans of kokodak in the world, I would be the one of them.
If there are 10 fans of kokodak in the world, I still would be the one of them.
If there is only one fan of kokodak in the world, that person would be me.
If there isn't any fan of kokodak in the world, then I no longer exist in the world.

kokodak, my lord.
kokodak, my light.
kokodak, my sun.
kokodak, my life.
kokodak, my soul.
kokodak, me.

**Comment by kokodak** [comment]
Hi! This is kokodak Bot. Please wait a moment, your guestbook comment is being registered.

**Comment by kokodak** [comment]
Thank you for your contribution!
